// Auto-Generated by FAKE; do not edit
namespace System
open System.Runtime.CompilerServices

[<assembly: InternalsVisibleToAttribute("Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] InternalsVisibleTo = "Tests"
